### ISSUE TITLE
Пересборка проекта. Режим разработки

### ISSUE THREAD

**Issue by belozyorcev** [voischev/bem-full-stack#14]
Как выглядит процесс разработки на данном проекте?
Каждый раз запускать ```gulp```, затем снова ```npm start```?

Или я не так что-то делаю?

**Comment by voischev** [comment]
В коробке так. Далее зависит от твоих скилов использования `gulp` ты можешь настроить вотчер как тебе угодно

**Comment by belozyorcev** [comment]
а в какой каталог собираются bemtree и bemhtml?

**Comment by voischev** [comment]
в `bundles/index/`

**Comment by belozyorcev** [comment]
посмотрел внимательней и нашёл

```build/bundles/index/```
